name: Daily Tips (test)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Hello
        shell: powershell
        run: |
          Write-Host "Testi toimii."

      - name: Call Ollama
        shell: powershell
        run: |
          Write-Host "Calling Ollama..."
          $response = ollama run llama3.1 "Anna yksi lyhyt vinkki pienoismallien rakentamiseen."
          Write-Host "Ollama response:"
          Write-Host $response
